### ISSUE TITLE
Bottom Navigation showing OVERFLOW

### ISSUE THREAD

**Issue by zionnite** [lukepighetti/salomon_bottom_bar#10]
Hello sir, 
good day, sir, I want to use this opportunity to thank you for an awesome  work you provides us with through this pulugin, but however, when I ran the code on my emulator (ios and android alike) it was perfect but when i ran it on my real device, it was showing an overflow

![WhatsApp Image 2021-09-08 at 8 55 53 PM](https://user-images.githubusercontent.com/10984801/132576945-86fca3a9-cd3d-446f-852d-0b3021bfaa77.jpeg)

**Comment by lukepighetti** [comment]
There is too much content to display on that screen width using this design pattern.

**Comment by zionnite** [comment]
> There is too much content to display on that screen width using this design pattern.

Alright Thanks
