### ISSUE TITLE
Missing Controller option

### ISSUE THREAD

**Issue by applicationsweb** [lukepighetti/salomon_bottom_bar#11]
Hello, i don't see the "controller" option in your widget. Is it normal ?

I need to have this option for change a tab from an other page.

**Comment by kamathprasad9** [comment]
You don't need a controller option as such. It works fine without one.
Check [this](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html) out for an example.

**Comment by lukepighetti** [comment]
`BottomNavigationBar` doesn't use a controller so we don't use a controller. See promise number 3 in the readme.

**Comment by applicationsweb** [comment]
I need controller option for changing tabs from a button for exemple. Look this url : https://stackoverflow.com/questions/50887790/flutter-changing-the-current-tab-in-tab-bar-view-using-a-button

Your plugin don't propose this option so i can't do it... 

So i change your plugin by this plugin : https://pub.dev/packages/persistent_bottom_nav_bar

Persistent_bottom_nav_bar have a controller option

**Comment by lukepighetti** [comment]
How does `BottomNavigationBar` do it? That's how we do it, and if it's not working we should fix it.

**Comment by applicationsweb** [comment]
Your competitors' plugins use the concept of Controller.

Look their documentation : https://pub.dev/documentation/persistent_bottom_nav_bar/latest/

**Comment by lukepighetti** [comment]
This package makes an explicit promise to use `BottomNavigationBar` semantics. I don't have competitors. There are other packages on pub that make different promises.
