### ISSUE TITLE
Background color?

### ISSUE THREAD

**Issue by rgbinnovation** [lukepighetti/salomon_bottom_bar#12]
Is there no way to change the background color of the bottom bar? I tried with:

  bottomNavigationBar: Theme(
          data: Theme.of(context).copyWith(canvasColor: Colors.red),
          child: SalomonBottomBar(.....))

.. but it won't work? Any ideas?

**Comment by lukepighetti** [comment]
The background is transparent, wrap it in a `DecoratedBox` or `Container` with a color specified
