### ISSUE TITLE
What is the font family used in the gif shown at pub.dev?

### ISSUE THREAD

**Issue by tomasweigenast** [lukepighetti/salomon_bottom_bar#18]
I wish to know :p

**Comment by lukepighetti** [comment]
I would contact the designer and ask, you should be able to find their contact info online

**Comment by tomasweigenast** [comment]
I thought I was made by you. So sorry

**Comment by zees98** [comment]
Hello Guys!
Can I know what font was used in the example? I require a similar font for a project but cant find its name. 

TIA
