### ISSUE TITLE
Feature request: onLongPress callback

### ISSUE THREAD

**Issue by steef435** [lukepighetti/salomon_bottom_bar#19]
Hello!

For [FluffyChat](https://gitlab.com/famedly/fluffychat) we would like to have a way to detect long presses on the items (to show a menu related to the item pressed). Is there currently any way to do this?

I first tried to add GestureDetectors to both the icon and the title, but it gets kind of finicky (some parts of the button still don't trigger).

Then I noticed that you used InkWells internally, so it would be easy to add a callback like so: https://github.com/steef435/salomon_bottom_bar/commit/82f359f9100eaeeb7d69542b62f15a9f8215c1ef. It works the same way as the onTap callback.

Is this something you are willing to add? (I'll create a PR.)

**Comment by lukepighetti** [comment]
Is it possible to do this with BottomNavigationBar?

If so, let's get this fixed.

If not, feel free to copy-paste `salomon_bottom_bar` into your private repo and close this issue.

**Comment by steef435** [comment]
I guess not.. we'll do it on our side then. Thank you!
