### ISSUE TITLE
title abrupt changes

### ISSUE THREAD

**Issue by bluemix** [lukepighetti/salomon_bottom_bar#22]
As you can see, the second item shows abrupt changes when switched from it to another item:

https://user-images.githubusercontent.com/3332274/151884180-1f04b016-2a94-45c5-b67f-be7071165c18.mp4

**Comment by lukepighetti** [comment]
I don't see any fidelity issues here, please re-open if you can provide a concrete comparison with the [Salomon spec on Dribble ](https://dribbble.com/shots/5925052-Google-Bottom-Bar-Navigation-Pattern/)

**Comment by lukepighetti** [comment]
Reopening: is this the same issue? 

Related to https://github.com/lukepighetti/salomon_bottom_bar/issues/26

**Comment by lukepighetti** [comment]
Let's track this in #26
