### ISSUE TITLE
Align buttons to left/right

### ISSUE THREAD

**Issue by banderberg** [lukepighetti/salomon_bottom_bar#24]
I have a scenario wherein my nav bar only has two buttons.  Currently one aligns left, the other aligns right.  How can I have both align to the left?

**Comment by lukepighetti** [comment]
What happens when you only put two items in BottomNavigationBar? We follow that API exactly. We will enforce whatever that API is.

**Comment by DriesCruyskens** [comment]
> What happens when you only put two items in BottomNavigationBar? We follow that API exactly. We will enforce whatever that API is.

Two items is pretty much unusable: 
![image](https://user-images.githubusercontent.com/26900172/155700697-6606164d-4835-430e-b0bb-07eccd36407a.png)

As oposed to how the original BottomNavigationBar spaces them out:
![image](https://user-images.githubusercontent.com/26900172/155701123-de63790f-cf34-4710-88de-3d3ca157342c.png)

@banderberg I forked the repo here `https://github.com/DriesCruyskens/salomon_bottom_bar` and added a MainAxisAlignment property so you can align at will. Will not create pull request becuase it does not follow BottonNavigationBar's API. Pubspec.yaml:
```
salomon_bottom_bar:
    git:
      url: git://github.com/DriesCruyskens/salomon_bottom_bar.git
      ref: main
```

**Comment by lukepighetti** [comment]
Sounds like this is a case we should handle. Thanks for documenting. Any ideas on how you would like to implement this? Does it go spaceAround if there's 2 items?

**Comment by DriesCruyskens** [comment]
I think spaceEvenly look better with this particular design. made pull request #25.
