### ISSUE TITLE
Delegate fields to SafeArea

### ISSUE THREAD

**Issue by swenhancer** [lukepighetti/salomon_bottom_bar#28]
Since `SafeArea` is now root of the `SalomonBottomBar` it would be handy if important `SafeArea` fields can be set trough `SalomonBottomBar`'s constructor. At the moment only the `minimum` field is available and other are missing:

```
  const SafeArea({
    Key? key,
    this.left = true,
    this.top = true,
    this.right = true,
    this.bottom = true,
    this.minimum = EdgeInsets.zero,
    this.maintainBottomViewPadding = false,
    required this.child,
  }) : assert(left != null),
       assert(top != null),
       assert(right != null),
       assert(bottom != null),
       super(key: key);
```

It would make sense adding the `left`, `top`, `right`, `bottom` and  `maintainBottomViewPadding` too.

**Comment by lukepighetti** [comment]
Hmm, this is interesting. I originally added SafeArea thinking it wouldn't be a breaking change since any existing SafeArea's should consume the area and continue to work as expected. But I may have made an assumption here. Can you tell me what's changed for you?

**Comment by swenhancer** [comment]
It adds unwanted padding at the top of the bar for me. Not sure why parent SafeAre didn't consume the unsafe paddings. I'll try to assemble a MRE until end of the week.

**Comment by swenhancer** [comment]
Hey @lukepighetti, I finally had time to go back to this. It seems that your assumption was correct. Parent `SafeArea` does consume the unsafe paddings. An oversight happened as I'm using the lib in an unconventional way - as a tab bar. 

<img width="220" alt="image" src="https://user-images.githubusercontent.com/100318392/162629445-d06a11a7-f6b5-4f99-9bbb-805790281239.png">

Thanks for the reply, feel free to close the issue.

**Comment by lukepighetti** [comment]
Thanks for clarifying and confirming, appreciate it!

What was your solution in your context?

**Comment by swenhancer** [comment]
> What was your solution in your context?

Adding a `SafeArea` as one of the widgets up in the hierarchy. 

First I tried this with just one level above (by wrapping the `SalomonBottomBar` with `SafeArea`), but that didn't work. This is why I opened the issue. It seems that `SafeArea` doesn't properly work inside the `BlocBuilder`. Once it was moved outside it started behaving as expected.

**Comment by lukepighetti** [comment]
I appreciate you documenting that here, thanks!

**Comment by gabzim** [comment]
I'm having an issue with this as well, since I'm trying to make it float, it took me a while to figure out why I couldn't center the bar.
