### ISSUE TITLE
Add badge indicators to SalomonBottomBarItem

### ISSUE THREAD

**Issue by dhorajiaabhishek** [lukepighetti/salomon_bottom_bar#29]
How can I add badges on SalomonBottomBarItem

**Comment by lukepighetti** [comment]
1. We don't have design for this in the original spec
2. `title` is a Widget, so you can put whatever you want in there

**Comment by lukepighetti** [comment]
We don't have this in the original spec, but I will see if we can get it

**Comment by lukepighetti** [comment]
The original designer was not available to provide an updated spec. My recommendation is to put your icon in a stack and position the badges where you need them.

Here are some ideas

![Ru9Ip9bM jpg-large](https://user-images.githubusercontent.com/666539/166147313-12555411-8154-4976-a3d8-f0c45342af9c.jpeg)

**Comment by adrianvintu** [comment]
You can add badges easily.

Use https://pub.dev/packages/badges

```
SalomonBottomBarItem(
        icon: BadgeWrapper(
                key: _communityBadgeGlobalKey,
                 initialNumber: chatMessageCount,
                 child: Icon(Icons.community)
                 title: Text('Community'),
      );
```
