### ISSUE TITLE
Add option to remove opacity from selected color.

### ISSUE THREAD

**Issue by vipafattal** [lukepighetti/salomon_bottom_bar#3]

**Comment by lukepighetti** [comment]
Is this doable with the Flutter BottomNavigationBar? If so, write up a quick description of how it's achieved and I'll implement the same API.

**Comment by vipafattal** [comment]
the selectedItemColor in SalomonBottomBar has an opacity by default is set to 0.1, more exactly, at the `Material` widget color.

**Comment by lukepighetti** [comment]
Just a heads up, I won't be merging anything that diverges from the BottomNavigationBar API. I don't have time to review your PR until later this week, but it landing will depend on if it adheres to the BNB API. Make sure you check the BNB API to see if the PR is viable. Thank you.

**Comment by lukepighetti** [comment]
Closed by https://github.com/lukepighetti/salomon_bottom_bar/pull/4
