### ISSUE TITLE
possibility to pass null on currentindex

### ISSUE THREAD

**Issue by eebeeDEV** [lukepighetti/salomon_bottom_bar#6]
Hi,

I'm using the SalomonBottomBar in a WEB app and it would be nice if it was possible to pass a null value to the currentindex.
This way none of the items would be selected.
When starting my application, I want to show a blank page with the app logo and no items selected.

The user then clicks on an item to go to the selected page.

Very nice Widget btw :)
Best,
eeBee

**Comment by eebeeDEV** [comment]
My bad, 
Setting the currentIndex to -1, does exactly what I need.
Please ignore my request above

**Comment by Ahmadre** [comment]
@eebeeDEV could you please close this issues, if you think it's resolved? Thanks :)
