### ISSUE TITLE
when use on web, the width is matching the browser, can we allow align center?

### ISSUE THREAD

**Issue by jeffreyliu8** [lukepighetti/salomon_bottom_bar#9]
![Screen Shot 2021-09-08 at 12 26 05 PM](https://user-images.githubusercontent.com/12398645/132572532-103c1c75-7547-4b08-adb2-262ab4334c8c.png)

**Comment by lukepighetti** [comment]
Does `BottomNavigationBar` act differently?

**Comment by Paul-cbt** [comment]
Hello, 
you can put a margin around the SalomonBottomBar, like this for example:
` margin: EdgeInsets.fromLTRB(
                                  MediaQuery.of(context).size.width > 700
                                      ? MediaQuery.of(context).size.width / 3
                                      : 40,
                                  5,
                                  MediaQuery.of(context).size.width > 700
                                      ? MediaQuery.of(context).size.width / 3
                                      : 40,
                                  10),
                           `

Best,
Paul

**Comment by lukepighetti** [comment]
Please feel free to reopen if we diverge from `BottomNavigationBar` behavior
